name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          ssh_config: |
            Host *
                StrictHostKeyChecking no
          script: |
            cd /var/www/led-app/LED-app
            git pull origin master
            npm install
            pm2 restart all   # Or whichever command restarts your application
